name: Build Obentou

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  windows-mingw:
    name: Windows MinGW Build
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install MSYS2 + MinGW
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-binutils
            mingw-w64-x86_64-make

      - name: Build with MinGW
        shell: msys2 {0}
        run: |
          mingw32-make -j8

      - name: Prepare Build Output
        shell: powershell
        run: |
          mkdir release
          cp *.exe release/
          cp SDL3.dll release/
          cp config.ini release/

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: obentou-windows
          path: release/

  web-emscripten:
    name: Emscripten Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Build with Emscripten
        run: emmake make emcc

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: obentou-web
          path: website/

  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: [windows-mingw, web-emscripten]
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: obentou-windows
          path: win-dist

      - name: Download Web Artifact
        uses: actions/download-artifact@v4
        with:
          name: obentou-web
          path: web-dist

      - name: Zip Artifacts
        run: |
          # Zip the content of win-dist into obentou-windows.zip
          cd win-dist && zip -r ../obentou-windows.zip ./* && cd ..
          
          # Zip the content of web-dist into obentou-web.zip
          cd web-dist && zip -r ../obentou-web.zip ./* && cd ..

      - name: Get commit message
        id: commit_msg
        run: |
          echo "message<<EOF" >> $GITHUB_OUTPUT
          git log -1 --pretty=%B >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            obentou-windows.zip
            obentou-web.zip
          body: ${{ steps.commit_msg.outputs.message }}